### ISSUE TITLE
General topics to turn into issues

### ISSUE THREAD

**Issue by dsberger** [code-newbies/js-tuesday-hangman#1]
Inserting guessed letters into HTML.
Dictionary with filter for words with less than five letters. -- with API?
Import file for dictionary

Level of difficulty, choosing word length based on difficulty.
Two-player version with one player entering word.

Figure out hanging man graphic.
Display of number of letters in the word.

Chart of letters that remain.
Clicking on letter to guess the letter.
Good guesses populate the word.
Bad guesses join the bad guesses section.

Game ending animations (good or bad)

Instant finish button (with points bonus/instant DEATH, all or nothing)
Leaderboard <-- maybe later, requires a DB
Social media integration, e.g. share your score on twitter.

Entension: category hint, build into dictionary (e.g. "animal")
Research categorized dictionaries

**Comment by nannigan** [comment]
I had a thought that would fit several steps, perhaps. 
When the word is 'initialized', into the game, first it is broken into an array of inidividual letters. The letters are then added to the dom with a  class on their html elements(<span></span>) that sets their visibilty to none. When the user clicks on a particular letter it toggles the visibilty of the instances of that letter so that they show up (where they've been hiding so to speak).

**Comment by simon-xiong-ca** [comment]
That's a great way to approach this! And how about having placeholders so the player knows how many letters they have left to guess?

**Comment by nannigan** [comment]
sure, the letters could be in spans with visibility none, which themselves would be contained by inline block `<li>` s or something that could have borders so you could see they were there...
maybe the border could change to green when the  correct letter shows up...
